# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - run: mkdir staging && cp target/*.war staging
    - run: pwd
    - run: ls -al    
    - uses: actions/upload-artifact@v1
      with:
        name: Package
        path: staging
    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        # Artifact name
        name: package
        # Destination path
        path: 
      #- name: Upload a Build Artifact via S3
    #  uses: ebuckthal/s3-upload-artifact@v7
    #  with:
        # bucket name
    #    bucket: githubaction
       # destination key in bucket
     #   key: test
       # file to upload
     #   path: https://s3.console.aws.amazon.com/s3/buckets/githubaction/CICD/?region=us-east-2
    #- name: deploy-action
    #  uses: madhuchittabathina/deploy-action@v0.1.0
